#:schema https://reuse.software/reuse-toml-v1.schema.json

version = 1

[[annotations]]
SPDX-FileCopyrightText = "Copyright Â© 2025 Pablo Castellazzi <pablo.castellazzi@icloud.com>"
SPDX-License-Identifier = "MIT"
precedence = "override"

path = [
    ".copier-answers.yml",
    ".coveragerc",
    ".cspell.dictionary.txt",
    ".cspell.json",
    ".gitignore",
    ".pdoc-theme/**",
    ".pre-commit-config.yaml",
    ".python-version",
    "GNUmakefile",
    "README.md",
    "conftest.py",
    "examples/**",
    "pyproject.toml",
    "ruff.toml",
    "src/**",
    "tests/**",
    "uv.lock",
]
